// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/comandas/{codigo}/abrir": {
            "post": {
                "description": "Porteiro escaneia/seleciona a comanda física e o sistema a marca como \"em_uso\", associando-a opcionalmente a uma mesa. Falha se a comanda não estiver com status \"disponivel\".",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Entregar comanda zerada ao cliente (US-07)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código físico da comanda (código de barras/QR)",
                        "name": "codigo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Mesa a associar à comanda (opcional)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handler.abrirComandaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Comanda"
                        }
                    },
                    "404": {
                        "description": "comanda não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "comanda não está disponível (em uso, paga ou cancelada)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Comanda": {
            "type": "object",
            "properties": {
                "abertaEm": {
                    "type": "string"
                },
                "codigoFisico": {
                    "type": "string"
                },
                "fechadaEm": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.StatusComanda"
                },
                "tableID": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                }
            }
        },
        "domain.StatusComanda": {
            "type": "string",
            "enum": [
                "disponivel",
                "em_uso",
                "paga",
                "cancelada"
            ],
            "x-enum-varnames": [
                "StatusDisponivel",
                "StatusEmUso",
                "StatusPaga",
                "StatusCancelada"
            ]
        },
        "handler.abrirComandaRequest": {
            "type": "object",
            "properties": {
                "table_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Merka API",
	Description:      "Sistema de comandas multi-tenant (churrascaria como primeira instância). Ver CLAUDE.md e docs/merka-planejamento.md para o contexto completo do domínio.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
