// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Valida login/senha e devolve um JWT contendo user_id, tenant_id e role_id, usado nas demais rotas via header Authorization: Bearer \u003ctoken\u003e.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Autenticar usuário",
                "parameters": [
                    {
                        "description": "Credenciais",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.loginResponse"
                        }
                    },
                    "400": {
                        "description": "corpo da requisição inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "login ou senha inválidos",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comandas/{codigo}/abrir": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Porteiro escaneia/seleciona a comanda física e o sistema a marca como \"em_uso\", associando-a opcionalmente a uma mesa. Falha se a comanda não estiver com status \"disponivel\". Requer autenticação (Authorization: Bearer \u003ctoken\u003e).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Entregar comanda zerada ao cliente (US-07)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código físico da comanda (código de barras/QR)",
                        "name": "codigo",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Mesa a associar à comanda (opcional)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handler.abrirComandaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Comanda"
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "comanda não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "comanda não está disponível (em uso, paga ou cancelada)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comandas/{codigo}/liberar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Porteiro escaneia a comanda na saída; se estiver paga (sem saldo devedor), o sistema libera de volta pro estoque (status volta a \"disponivel\"). Se ainda tiver saldo pendente, bloqueia com erro claro.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Receber comanda na saída e validar zeramento (US-08)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Código físico da comanda",
                        "name": "codigo",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Comanda"
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "comanda não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "comanda ainda não foi paga",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comandas/{id}/cancelar": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Gestor/Admin Super (permissão \"cancelar_comanda\"). Zera todos os itens/pesos lançados (marcados como removidos, nunca apagados), marca a comanda como cancelada e a libera de volta pro estoque. Exige motivo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Cancelar comanda totalmente (US-15)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Motivo do cancelamento",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.cancelarComandaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Comanda"
                        }
                    },
                    "400": {
                        "description": "motivo obrigatório",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "comanda não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "comanda não está em uso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comandas/{id}/desconto": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Gestor, Admin Super ou Caixa (permissão \"aplicar_desconto\"). Tipo \"valor_fixo\" ou \"percentual\", sempre com motivo — bloqueia se o desconto resultar em total negativo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Aplicar desconto manual (US-17)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tipo, valor e motivo do desconto",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.aplicarDescontoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Discount"
                        }
                    },
                    "400": {
                        "description": "motivo obrigatório ou tipo inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "desconto resultaria em valor negativo",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comandas/{id}/itens": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Garçom lança um item do cardápio (bebida, sobremesa, etc.) na comanda. Se a comanda já não aceitar lançamento (paga/cancelada), o lançamento é rejeitado e um alerta é gravado em sync_alerts para o Gestor (conflito de sincronização).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Lançar item unitário na comanda (US-11)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Produto e quantidade",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.lancarItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.OrderItem"
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "comanda ou produto não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "comanda já finalizada — lançamento rejeitado, alerta gravado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comandas/{id}/mesa": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permitida a qualquer perfil autenticado (sem checagem de permissão granular, por decisão do planejamento) — mantém todos os itens/pesos já lançados intactos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Transferir comanda entre mesas (US-16)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nova mesa",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.transferirMesaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Comanda"
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "comanda ou mesa não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "comanda não está em uso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/comandas/{id}/pesos": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Balança lê o peso bruto do prato; o backend calcula (peso_bruto - tara) * preco_por_kg e lança em order_items. Se a comanda já não aceitar lançamento (paga/cancelada), o lançamento é rejeitado e um alerta é gravado em sync_alerts para o Gestor (conflito de sincronização).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "comandas"
                ],
                "summary": "Registrar peso de item na comanda (US-09)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID da comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Produto pesado e peso bruto lido",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.registrarPesoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.OrderItem"
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "comanda ou produto não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "comanda já finalizada — lançamento rejeitado, alerta gravado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/order-items/{id}/estornar": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Operador de Balança remove um lançamento de peso já feito (ex: cliente foi e voltou pra repetir). O registro original é preservado — muda só o status pra \"estornado\". Exige motivo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order-items"
                ],
                "summary": "Estornar registro de peso (US-10)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do order_item",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Motivo do estorno",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.motivoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OrderItem"
                        }
                    },
                    "400": {
                        "description": "motivo obrigatório",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "item não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "item já foi removido ou estornado anteriormente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/order-items/{id}/remover": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Garçom remove um item unitário lançado por engano ou a pedido do cliente. O registro original é preservado — muda só o status pra \"removido\". Exige motivo.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "order-items"
                ],
                "summary": "Remover item lançado da comanda (US-12)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do order_item",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Motivo da remoção",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.motivoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.OrderItem"
                        }
                    },
                    "400": {
                        "description": "motivo obrigatório",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "item não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "item já foi removido ou estornado anteriormente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/pagamentos": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Soma o total ativo (itens + pesos, excluindo removidos/estornados) das comandas informadas — que podem ser N comandas de uma mesma mesa — e confere contra a soma dos pagamentos parciais informados (suporta pagamento misto). Se bater, grava um payment por método, liga todas as comandas via payment_comandas e marca as comandas como \"paga\". Não emite nota fiscal ainda (ver TODO no usecase para US-14/emissão de NFC-e).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pagamentos"
                ],
                "summary": "Fechar pagamento de uma ou mais comandas (US-13 + US-14)",
                "parameters": [
                    {
                        "description": "Comandas a fechar e pagamentos parciais",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.fecharPagamentoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.fecharPagamentoResponse"
                        }
                    },
                    "400": {
                        "description": "corpo inválido, método inválido ou soma dos pagamentos não bate com o total",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "alguma comanda não encontrada",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/perfis": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin Super e Gestor podem ver — ver comentário em RegistrarRotas sobre a permissão reaproveitada.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "perfis"
                ],
                "summary": "Listar perfis do tenant",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Role"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Admin Super (permissão \"criar_perfil\"). Recebe nome e uma lista de chaves de permissão já existentes no catálogo — cria o role e as linhas correspondentes em role_permissions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "perfis"
                ],
                "summary": "Criar perfil customizado (US-02)",
                "parameters": [
                    {
                        "description": "Nome do perfil e chaves de permissão",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.criarPerfilRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Role"
                        }
                    },
                    "400": {
                        "description": "nome obrigatório ou permissão inexistente no catálogo",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "já existe um perfil com esse nome",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/perfis/{id}/permissoes": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Admin Super (permissão \"criar_perfil\"). Bloqueia perfis de sistema (ex: \"Admin Super\") — imutáveis, pra não travar o próprio acesso do sistema.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "perfis"
                ],
                "summary": "Substituir as permissões de um perfil (US-02)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do perfil",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo conjunto de permissões",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.editarPermissoesPerfilRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Role"
                        }
                    },
                    "400": {
                        "description": "permissão inexistente no catálogo",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "perfil não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "perfil de sistema é imutável",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/permissoes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin Super e Gestor podem ver — mesma permissão reaproveitada de ListarPerfis.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "perfis"
                ],
                "summary": "Listar catálogo fixo de permissões",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.PermissionCatalogo"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/produtos": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Qualquer perfil autenticado — usado por garçom/balança pra escolher o que lançar (US-09/US-11).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Listar catálogo de produtos ativos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Product"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Admin Super, Gestor ou Caixa (permissão \"cadastrar_produto\"). tipo_cobranca \"unitario\" exige preco_unitario \u003e 0; tipo_cobranca \"peso\" exige preco_por_kg \u003e 0 (tara_kg opcional, default 0). Grava a primeira linha em product_price_history para produtos do tipo peso.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Cadastrar novo produto no catálogo (US-21)",
                "parameters": [
                    {
                        "description": "Dados do produto",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.cadastrarProdutoRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    },
                    "400": {
                        "description": "campo obrigatório ausente ou tipo_cobranca inválido",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/produtos/{id}/preco-peso": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Admin Super, Gestor, Caixa ou Balança (permissão \"configurar_preco_peso\") — ajuste operacional do dia a dia, diferente das demais configurações estruturais. Só se aplica a produtos do tipo peso. Grava o histórico da alteração em product_price_history.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "produtos"
                ],
                "summary": "Configurar preço/kg e tara de um produto (US-20)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Novo preço/kg e/ou tara (ao menos um)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.configurarPrecoPesoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.Product"
                        }
                    },
                    "400": {
                        "description": "nada para atualizar",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "produto não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "produto não é do tipo peso",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/usuarios": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Admin Super ou Gestor (permissão \"criar_usuario\"). Valida que role_id pertence ao mesmo tenant. Senha é sempre gravada como hash bcrypt, nunca em texto puro.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "usuarios"
                ],
                "summary": "Criar usuário (US-01)",
                "parameters": [
                    {
                        "description": "Dados do novo usuário",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.criarUsuarioRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handler.usuarioResponse"
                        }
                    },
                    "400": {
                        "description": "campo obrigatório ausente ou senha curta",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "perfil (role) não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "já existe um usuário com esse login",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/usuarios/{id}/desativar": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Restrito a Admin Super ou Gestor (permissão \"criar_usuario\"). Nunca deleta — o usuário perde acesso imediatamente (login passa a falhar), mas o histórico dele em audit_log permanece intacto.",
                "tags": [
                    "usuarios"
                ],
                "summary": "Desativar usuário (US-01)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do usuário",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "token ausente, inválido ou expirado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "usuário sem permissão para esta ação",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "usuário não encontrado",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "erro interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Comanda": {
            "type": "object",
            "properties": {
                "abertaEm": {
                    "type": "string"
                },
                "codigoFisico": {
                    "type": "string"
                },
                "fechadaEm": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.StatusComanda"
                },
                "tableID": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                }
            }
        },
        "domain.Discount": {
            "type": "object",
            "properties": {
                "aplicadoEm": {
                    "type": "string"
                },
                "aplicadoPor": {
                    "type": "string"
                },
                "comandaID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "motivo": {
                    "type": "string"
                },
                "tenantID": {
                    "type": "string"
                },
                "tipo": {
                    "$ref": "#/definitions/domain.TipoDesconto"
                },
                "valor": {
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "domain.OrderItem": {
            "type": "object",
            "properties": {
                "comandaID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lancadoEm": {
                    "type": "string"
                },
                "lancadoPor": {
                    "type": "string"
                },
                "motivoRemocao": {
                    "type": "string"
                },
                "pesoKg": {
                    "description": "usado para itens de peso (peso líquido, já descontada a tara)",
                    "type": "number",
                    "format": "float64"
                },
                "productID": {
                    "type": "string"
                },
                "quantidade": {
                    "description": "usado para itens unitários",
                    "type": "number",
                    "format": "float64"
                },
                "removidoEm": {
                    "type": "string"
                },
                "removidoPor": {
                    "description": "Preenchidos só quando Status != ativo (US-10/US-12) — o lançamento\noriginal nunca é apagado, só marcado.",
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/domain.StatusOrderItem"
                },
                "tenantID": {
                    "type": "string"
                },
                "valor": {
                    "type": "number",
                    "format": "float64"
                }
            }
        },
        "domain.Permissao": {
            "type": "string",
            "enum": [
                "criar_usuario",
                "criar_perfil",
                "configurar_sistema",
                "ver_auditoria",
                "ver_relatorios",
                "lancar_item",
                "remover_item",
                "registrar_peso",
                "estornar_peso",
                "transferir_mesa",
                "aplicar_desconto",
                "cancelar_comanda",
                "processar_pagamento",
                "entregar_comanda",
                "cadastrar_produto",
                "configurar_preco_peso"
            ],
            "x-enum-varnames": [
                "PermissaoCriarUsuario",
                "PermissaoCriarPerfil",
                "PermissaoConfigurarSistema",
                "PermissaoVerAuditoria",
                "PermissaoVerRelatorios",
                "PermissaoLancarItem",
                "PermissaoRemoverItem",
                "PermissaoRegistrarPeso",
                "PermissaoEstornarPeso",
                "PermissaoTransferirMesa",
                "PermissaoAplicarDesconto",
                "PermissaoCancelarComanda",
                "PermissaoProcessarPagamento",
                "PermissaoEntregarComanda",
                "PermissaoCadastrarProduto",
                "PermissaoConfigurarPrecoPeso"
            ]
        },
        "domain.PermissionCatalogo": {
            "type": "object",
            "properties": {
                "chave": {
                    "$ref": "#/definitions/domain.Permissao"
                },
                "descricao": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "domain.Product": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "categoryID": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "precoPorKg": {
                    "description": "usado quando TipoCobranca == TipoCobrancaPeso",
                    "type": "number",
                    "format": "float64"
                },
                "precoUnitario": {
                    "description": "usado quando TipoCobranca == TipoCobrancaUnitario",
                    "type": "number",
                    "format": "float64"
                },
                "taraKg": {
                    "description": "peso do prato/recipiente, descontado do peso bruto lido na balança",
                    "type": "number",
                    "format": "float64"
                },
                "tenantID": {
                    "type": "string"
                },
                "tipoCobranca": {
                    "$ref": "#/definitions/domain.TipoCobranca"
                }
            }
        },
        "domain.Role": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "sistema": {
                    "type": "boolean"
                },
                "tenantID": {
                    "type": "string"
                }
            }
        },
        "domain.StatusComanda": {
            "type": "string",
            "enum": [
                "disponivel",
                "em_uso",
                "paga",
                "cancelada"
            ],
            "x-enum-varnames": [
                "StatusDisponivel",
                "StatusEmUso",
                "StatusPaga",
                "StatusCancelada"
            ]
        },
        "domain.StatusOrderItem": {
            "type": "string",
            "enum": [
                "ativo",
                "removido",
                "estornado"
            ],
            "x-enum-varnames": [
                "StatusItemAtivo",
                "StatusItemRemovido",
                "StatusItemEstornado"
            ]
        },
        "domain.TipoCobranca": {
            "type": "string",
            "enum": [
                "unitario",
                "peso"
            ],
            "x-enum-varnames": [
                "TipoCobrancaUnitario",
                "TipoCobrancaPeso"
            ]
        },
        "domain.TipoDesconto": {
            "type": "string",
            "enum": [
                "valor_fixo",
                "percentual"
            ],
            "x-enum-varnames": [
                "DescontoValorFixo",
                "DescontoPercentual"
            ]
        },
        "handler.abrirComandaRequest": {
            "type": "object",
            "properties": {
                "table_id": {
                    "type": "string"
                }
            }
        },
        "handler.aplicarDescontoRequest": {
            "type": "object",
            "properties": {
                "motivo": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "handler.cadastrarProdutoRequest": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "preco_por_kg": {
                    "type": "number"
                },
                "preco_unitario": {
                    "type": "number"
                },
                "tara_kg": {
                    "type": "number"
                },
                "tipo_cobranca": {
                    "type": "string"
                }
            }
        },
        "handler.cancelarComandaRequest": {
            "type": "object",
            "properties": {
                "motivo": {
                    "type": "string"
                }
            }
        },
        "handler.configurarPrecoPesoRequest": {
            "type": "object",
            "properties": {
                "preco_por_kg": {
                    "type": "number"
                },
                "tara_kg": {
                    "type": "number"
                }
            }
        },
        "handler.criarPerfilRequest": {
            "type": "object",
            "properties": {
                "nome": {
                    "type": "string"
                },
                "permissoes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.criarUsuarioRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "role_id": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "handler.editarPermissoesPerfilRequest": {
            "type": "object",
            "properties": {
                "permissoes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.fecharPagamentoRequest": {
            "type": "object",
            "properties": {
                "comanda_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "pagamentos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.pagamentoParcialRequest"
                    }
                }
            }
        },
        "handler.fecharPagamentoResponse": {
            "type": "object",
            "properties": {
                "payment_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handler.lancarItemRequest": {
            "type": "object",
            "properties": {
                "product_id": {
                    "type": "string"
                },
                "quantidade": {
                    "type": "number"
                }
            }
        },
        "handler.loginRequest": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "senha": {
                    "type": "string"
                }
            }
        },
        "handler.loginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "handler.motivoRequest": {
            "type": "object",
            "properties": {
                "motivo": {
                    "type": "string"
                }
            }
        },
        "handler.pagamentoParcialRequest": {
            "type": "object",
            "properties": {
                "metodo": {
                    "type": "string"
                },
                "valor": {
                    "type": "number"
                }
            }
        },
        "handler.registrarPesoRequest": {
            "type": "object",
            "properties": {
                "peso_bruto": {
                    "type": "number"
                },
                "product_id": {
                    "type": "string"
                }
            }
        },
        "handler.transferirMesaRequest": {
            "type": "object",
            "properties": {
                "table_id": {
                    "type": "string"
                }
            }
        },
        "handler.usuarioResponse": {
            "type": "object",
            "properties": {
                "ativo": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "nome": {
                    "type": "string"
                },
                "role_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Informe \"Bearer \u003ctoken\u003e\" (token obtido em POST /auth/login)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Merka API",
	Description:      "Sistema de comandas multi-tenant (churrascaria como primeira instância). Ver CLAUDE.md e docs/merka-planejamento.md para o contexto completo do domínio.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
